// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package warehousedb

import (
	"context"
)

type Querier interface {
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (CreateWarehouseRow, error)
	DisableWarehouse(ctx context.Context, id int64) (DisableWarehouseRow, error)
	GetWarehouseByID(ctx context.Context, id int64) (GetWarehouseByIDRow, error)
	GetWarehouseReference(ctx context.Context, id int64) (GetWarehouseReferenceRow, error)
	ListWarehouses(ctx context.Context, arg ListWarehousesParams) ([]ListWarehousesRow, error)
	SoftDeleteWarehouse(ctx context.Context, id int64) (int64, error)
	UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (UpdateWarehouseRow, error)
	WarehouseCodeExists(ctx context.Context, arg WarehouseCodeExistsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
