// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: warehouses.sql

package warehousedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (code, name, type, status, location, contact_name, contact_phone, remark)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id,
          code,
          name,
          type,
          status,
          location,
          contact_name,
          contact_phone,
          remark,
          created_at,
          updated_at
`

type CreateWarehouseParams struct {
	Code         string  `db:"code" json:"code"`
	Name         string  `db:"name" json:"name"`
	Type         string  `db:"type" json:"type"`
	Status       string  `db:"status" json:"status"`
	Location     *string `db:"location" json:"location"`
	ContactName  *string `db:"contact_name" json:"contact_name"`
	ContactPhone *string `db:"contact_phone" json:"contact_phone"`
	Remark       *string `db:"remark" json:"remark"`
}

type CreateWarehouseRow struct {
	ID           int64              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Status       string             `db:"status" json:"status"`
	Location     *string            `db:"location" json:"location"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	Remark       *string            `db:"remark" json:"remark"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (CreateWarehouseRow, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Location,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
	)
	var i CreateWarehouseRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Location,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableWarehouse = `-- name: DisableWarehouse :one
UPDATE warehouses
SET status = 'inactive',
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          code,
          name,
          type,
          status,
          location,
          contact_name,
          contact_phone,
          remark,
          created_at,
          updated_at
`

type DisableWarehouseRow struct {
	ID           int64              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Status       string             `db:"status" json:"status"`
	Location     *string            `db:"location" json:"location"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	Remark       *string            `db:"remark" json:"remark"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DisableWarehouse(ctx context.Context, id int64) (DisableWarehouseRow, error) {
	row := q.db.QueryRow(ctx, disableWarehouse, id)
	var i DisableWarehouseRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Location,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehouseByID = `-- name: GetWarehouseByID :one
SELECT id,
       code,
       name,
       type,
       status,
       location,
       contact_name,
       contact_phone,
       remark,
       created_at,
       updated_at
FROM warehouses
WHERE id = $1
  AND deleted_at IS NULL
`

type GetWarehouseByIDRow struct {
	ID           int64              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Status       string             `db:"status" json:"status"`
	Location     *string            `db:"location" json:"location"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	Remark       *string            `db:"remark" json:"remark"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetWarehouseByID(ctx context.Context, id int64) (GetWarehouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getWarehouseByID, id)
	var i GetWarehouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Location,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id,
       code,
       name,
       type,
       status,
       location,
       contact_name,
       contact_phone,
       remark,
       created_at,
       updated_at
FROM warehouses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR type = $2::text)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListWarehousesParams struct {
	Status *string `db:"status" json:"status"`
	Type   *string `db:"type" json:"type"`
	Offset int32   `db:"offset" json:"offset"`
	Limit  int32   `db:"limit" json:"limit"`
}

type ListWarehousesRow struct {
	ID           int64              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Status       string             `db:"status" json:"status"`
	Location     *string            `db:"location" json:"location"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	Remark       *string            `db:"remark" json:"remark"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListWarehouses(ctx context.Context, arg ListWarehousesParams) ([]ListWarehousesRow, error) {
	rows, err := q.db.Query(ctx, listWarehouses,
		arg.Status,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWarehousesRow
	for rows.Next() {
		var i ListWarehousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Location,
			&i.ContactName,
			&i.ContactPhone,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWarehouse = `-- name: SoftDeleteWarehouse :execrows
UPDATE warehouses
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWarehouse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWarehouse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses
SET code = $2,
    name = $3,
    type = $4,
    status = $5,
    location = $6,
    contact_name = $7,
    contact_phone = $8,
    remark = $9,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          code,
          name,
          type,
          status,
          location,
          contact_name,
          contact_phone,
          remark,
          created_at,
          updated_at
`

type UpdateWarehouseParams struct {
	ID           int64   `db:"id" json:"id"`
	Code         string  `db:"code" json:"code"`
	Name         string  `db:"name" json:"name"`
	Type         string  `db:"type" json:"type"`
	Status       string  `db:"status" json:"status"`
	Location     *string `db:"location" json:"location"`
	ContactName  *string `db:"contact_name" json:"contact_name"`
	ContactPhone *string `db:"contact_phone" json:"contact_phone"`
	Remark       *string `db:"remark" json:"remark"`
}

type UpdateWarehouseRow struct {
	ID           int64              `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Status       string             `db:"status" json:"status"`
	Location     *string            `db:"location" json:"location"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	Remark       *string            `db:"remark" json:"remark"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (UpdateWarehouseRow, error) {
	row := q.db.QueryRow(ctx, updateWarehouse,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Location,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
	)
	var i UpdateWarehouseRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Location,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const warehouseCodeExists = `-- name: WarehouseCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM warehouses
    WHERE code = $1
      AND deleted_at IS NULL
      AND ($2::bigint = 0 OR id <> $2::bigint)
) AS exists
`

type WarehouseCodeExistsParams struct {
	Code      string `db:"code" json:"code"`
	ExcludeID int64  `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) WarehouseCodeExists(ctx context.Context, arg WarehouseCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, warehouseCodeExists, arg.Code, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
