// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package skudb

import (
	"context"
)

type Querier interface {
	ActiveSKUExistsForMaterial(ctx context.Context, arg ActiveSKUExistsForMaterialParams) (bool, error)
	CreateSKU(ctx context.Context, arg CreateSKUParams) (CreateSKURow, error)
	GetSKUByID(ctx context.Context, id int64) (GetSKUByIDRow, error)
	ListSKUs(ctx context.Context, arg ListSKUsParams) ([]ListSKUsRow, error)
	SKUCodeExists(ctx context.Context, arg SKUCodeExistsParams) (bool, error)
	SoftDeleteSKU(ctx context.Context, id int64) (int64, error)
	UpdateSKU(ctx context.Context, arg UpdateSKUParams) (UpdateSKURow, error)
}

var _ Querier = (*Queries)(nil)
