// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: skus.sql

package skudb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSKU = `-- name: CreateSKU :one
INSERT INTO skus (material_id, code, name, unit_id, status, remark)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id,
          material_id,
          code,
          name,
          unit_id,
          status,
          remark,
          created_at,
          updated_at
`

type CreateSKUParams struct {
	MaterialID int64   `db:"material_id" json:"material_id"`
	Code       string  `db:"code" json:"code"`
	Name       string  `db:"name" json:"name"`
	UnitID     int64   `db:"unit_id" json:"unit_id"`
	Status     string  `db:"status" json:"status"`
	Remark     *string `db:"remark" json:"remark"`
}

type CreateSKURow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	UnitID     int64              `db:"unit_id" json:"unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) (CreateSKURow, error) {
	row := q.db.QueryRow(ctx, createSKU,
		arg.MaterialID,
		arg.Code,
		arg.Name,
		arg.UnitID,
		arg.Status,
		arg.Remark,
	)
	var i CreateSKURow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Code,
		&i.Name,
		&i.UnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSKUByID = `-- name: GetSKUByID :one
SELECT id,
       material_id,
       code,
       name,
       unit_id,
       status,
       remark,
       created_at,
       updated_at
FROM skus
WHERE id = $1
  AND deleted_at IS NULL
`

type GetSKUByIDRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	UnitID     int64              `db:"unit_id" json:"unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSKUByID(ctx context.Context, id int64) (GetSKUByIDRow, error) {
	row := q.db.QueryRow(ctx, getSKUByID, id)
	var i GetSKUByIDRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Code,
		&i.Name,
		&i.UnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSKUReference = `-- name: GetSKUReference :one
SELECT id,
       code,
       name,
       deleted_at
FROM skus
WHERE id = $1
`

type GetSKUReferenceRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) GetSKUReference(ctx context.Context, id int64) (GetSKUReferenceRow, error) {
	row := q.db.QueryRow(ctx, getSKUReference, id)
	var i GetSKUReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const listSKUs = `-- name: ListSKUs :many
SELECT id,
       material_id,
       code,
       name,
       unit_id,
       status,
       remark,
       created_at,
       updated_at
FROM skus
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint IS NULL OR material_id = $2::bigint)
  AND ($3::bigint IS NULL OR unit_id = $3::bigint)
ORDER BY id DESC
LIMIT $5 OFFSET $4
`

type ListSKUsParams struct {
	Status     *string `db:"status" json:"status"`
	MaterialID *int64  `db:"material_id" json:"material_id"`
	UnitID     *int64  `db:"unit_id" json:"unit_id"`
	Offset     int32   `db:"offset" json:"offset"`
	Limit      int32   `db:"limit" json:"limit"`
}

type ListSKUsRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	UnitID     int64              `db:"unit_id" json:"unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSKUs(ctx context.Context, arg ListSKUsParams) ([]ListSKUsRow, error) {
	rows, err := q.db.Query(ctx, listSKUs,
		arg.Status,
		arg.MaterialID,
		arg.UnitID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSKUsRow
	for rows.Next() {
		var i ListSKUsRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Code,
			&i.Name,
			&i.UnitID,
			&i.Status,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sKUCodeExists = `-- name: SKUCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM skus
    WHERE code = $1
      AND deleted_at IS NULL
      AND ($2::bigint = 0 OR id <> $2::bigint)
) AS exists
`

type SKUCodeExistsParams struct {
	Code      string `db:"code" json:"code"`
	ExcludeID int64  `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) SKUCodeExists(ctx context.Context, arg SKUCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sKUCodeExists, arg.Code, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSKU = `-- name: SoftDeleteSKU :execrows
UPDATE skus
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSKU(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSKU, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSKU = `-- name: UpdateSKU :one
UPDATE skus
SET material_id = $2,
    code = $3,
    name = $4,
    unit_id = $5,
    status = $6,
    remark = $7,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          material_id,
          code,
          name,
          unit_id,
          status,
          remark,
          created_at,
          updated_at
`

type UpdateSKUParams struct {
	ID         int64   `db:"id" json:"id"`
	MaterialID int64   `db:"material_id" json:"material_id"`
	Code       string  `db:"code" json:"code"`
	Name       string  `db:"name" json:"name"`
	UnitID     int64   `db:"unit_id" json:"unit_id"`
	Status     string  `db:"status" json:"status"`
	Remark     *string `db:"remark" json:"remark"`
}

type UpdateSKURow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	UnitID     int64              `db:"unit_id" json:"unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSKU(ctx context.Context, arg UpdateSKUParams) (UpdateSKURow, error) {
	row := q.db.QueryRow(ctx, updateSKU,
		arg.ID,
		arg.MaterialID,
		arg.Code,
		arg.Name,
		arg.UnitID,
		arg.Status,
		arg.Remark,
	)
	var i UpdateSKURow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Code,
		&i.Name,
		&i.UnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
