// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: materials.sql

package materialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (code, name, category_id, base_unit_id, status, remark)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id,
          code,
          name,
          category_id,
          base_unit_id,
          status,
          remark,
          created_at,
          updated_at
`

type CreateMaterialParams struct {
	Code       string  `db:"code" json:"code"`
	Name       string  `db:"name" json:"name"`
	CategoryID int64   `db:"category_id" json:"category_id"`
	BaseUnitID int64   `db:"base_unit_id" json:"base_unit_id"`
	Status     string  `db:"status" json:"status"`
	Remark     *string `db:"remark" json:"remark"`
}

type CreateMaterialRow struct {
	ID         int64              `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	CategoryID int64              `db:"category_id" json:"category_id"`
	BaseUnitID int64              `db:"base_unit_id" json:"base_unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (CreateMaterialRow, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.Code,
		arg.Name,
		arg.CategoryID,
		arg.BaseUnitID,
		arg.Status,
		arg.Remark,
	)
	var i CreateMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CategoryID,
		&i.BaseUnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT id,
       code,
       name,
       category_id,
       base_unit_id,
       status,
       remark,
       created_at,
       updated_at
FROM materials
WHERE id = $1
  AND deleted_at IS NULL
`

type GetMaterialByIDRow struct {
	ID         int64              `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	CategoryID int64              `db:"category_id" json:"category_id"`
	BaseUnitID int64              `db:"base_unit_id" json:"base_unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMaterialByID(ctx context.Context, id int64) (GetMaterialByIDRow, error) {
	row := q.db.QueryRow(ctx, getMaterialByID, id)
	var i GetMaterialByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CategoryID,
		&i.BaseUnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterials = `-- name: ListMaterials :many
SELECT id,
       code,
       name,
       category_id,
       base_unit_id,
       status,
       remark,
       created_at,
       updated_at
FROM materials
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint IS NULL OR category_id = $2::bigint)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListMaterialsParams struct {
	Status     *string `db:"status" json:"status"`
	CategoryID *int64  `db:"category_id" json:"category_id"`
	Offset     int32   `db:"offset" json:"offset"`
	Limit      int32   `db:"limit" json:"limit"`
}

type ListMaterialsRow struct {
	ID         int64              `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	CategoryID int64              `db:"category_id" json:"category_id"`
	BaseUnitID int64              `db:"base_unit_id" json:"base_unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMaterials(ctx context.Context, arg ListMaterialsParams) ([]ListMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listMaterials,
		arg.Status,
		arg.CategoryID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialsRow
	for rows.Next() {
		var i ListMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CategoryID,
			&i.BaseUnitID,
			&i.Status,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialCategoryExists = `-- name: MaterialCategoryExists :one
SELECT EXISTS (
    SELECT 1
    FROM material_categories
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) MaterialCategoryExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, materialCategoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const materialCodeExists = `-- name: MaterialCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM materials
    WHERE code = $1
      AND deleted_at IS NULL
      AND ($2::bigint = 0 OR id <> $2::bigint)
) AS exists
`

type MaterialCodeExistsParams struct {
	Code      string `db:"code" json:"code"`
	ExcludeID int64  `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) MaterialCodeExists(ctx context.Context, arg MaterialCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, materialCodeExists, arg.Code, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteMaterial = `-- name: SoftDeleteMaterial :execrows
UPDATE materials
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaterial(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMaterial, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unitExists = `-- name: UnitExists :one
SELECT EXISTS (
    SELECT 1
    FROM units
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) UnitExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, unitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET code = $2,
    name = $3,
    category_id = $4,
    base_unit_id = $5,
    status = $6,
    remark = $7,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          code,
          name,
          category_id,
          base_unit_id,
          status,
          remark,
          created_at,
          updated_at
`

type UpdateMaterialParams struct {
	ID         int64   `db:"id" json:"id"`
	Code       string  `db:"code" json:"code"`
	Name       string  `db:"name" json:"name"`
	CategoryID int64   `db:"category_id" json:"category_id"`
	BaseUnitID int64   `db:"base_unit_id" json:"base_unit_id"`
	Status     string  `db:"status" json:"status"`
	Remark     *string `db:"remark" json:"remark"`
}

type UpdateMaterialRow struct {
	ID         int64              `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	CategoryID int64              `db:"category_id" json:"category_id"`
	BaseUnitID int64              `db:"base_unit_id" json:"base_unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (UpdateMaterialRow, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.CategoryID,
		arg.BaseUnitID,
		arg.Status,
		arg.Remark,
	)
	var i UpdateMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CategoryID,
		&i.BaseUnitID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
