// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: material_unit_conversions.sql

package materialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterialUnitConversion = `-- name: CreateMaterialUnitConversion :one
INSERT INTO material_unit_conversions (material_id, from_unit_id, to_unit_id, factor)
VALUES ($1, $2, $3, $4)
RETURNING id,
          material_id,
          from_unit_id,
          to_unit_id,
          factor,
          created_at,
          updated_at
`

type CreateMaterialUnitConversionParams struct {
	MaterialID int64          `db:"material_id" json:"material_id"`
	FromUnitID int64          `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64          `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric `db:"factor" json:"factor"`
}

type CreateMaterialUnitConversionRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	FromUnitID int64              `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64              `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric     `db:"factor" json:"factor"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMaterialUnitConversion(ctx context.Context, arg CreateMaterialUnitConversionParams) (CreateMaterialUnitConversionRow, error) {
	row := q.db.QueryRow(ctx, createMaterialUnitConversion,
		arg.MaterialID,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.Factor,
	)
	var i CreateMaterialUnitConversionRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.Factor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialUnitConversionByID = `-- name: GetMaterialUnitConversionByID :one
SELECT id,
       material_id,
       from_unit_id,
       to_unit_id,
       factor,
       created_at,
       updated_at
FROM material_unit_conversions
WHERE id = $1::bigint
  AND material_id = $2::bigint
  AND deleted_at IS NULL
`

type GetMaterialUnitConversionByIDParams struct {
	ID         int64 `db:"id" json:"id"`
	MaterialID int64 `db:"material_id" json:"material_id"`
}

type GetMaterialUnitConversionByIDRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	FromUnitID int64              `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64              `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric     `db:"factor" json:"factor"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMaterialUnitConversionByID(ctx context.Context, arg GetMaterialUnitConversionByIDParams) (GetMaterialUnitConversionByIDRow, error) {
	row := q.db.QueryRow(ctx, getMaterialUnitConversionByID, arg.ID, arg.MaterialID)
	var i GetMaterialUnitConversionByIDRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.Factor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterialUnitConversions = `-- name: ListMaterialUnitConversions :many
SELECT id,
       material_id,
       from_unit_id,
       to_unit_id,
       factor,
       created_at,
       updated_at
FROM material_unit_conversions
WHERE material_id = $1::bigint
  AND deleted_at IS NULL
  AND ($2::bigint IS NULL OR from_unit_id = $2::bigint)
  AND ($3::bigint IS NULL OR to_unit_id = $3::bigint)
ORDER BY id DESC
LIMIT $5 OFFSET $4
`

type ListMaterialUnitConversionsParams struct {
	MaterialID int64  `db:"material_id" json:"material_id"`
	FromUnitID *int64 `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   *int64 `db:"to_unit_id" json:"to_unit_id"`
	Offset     int32  `db:"offset" json:"offset"`
	Limit      int32  `db:"limit" json:"limit"`
}

type ListMaterialUnitConversionsRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	FromUnitID int64              `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64              `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric     `db:"factor" json:"factor"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMaterialUnitConversions(ctx context.Context, arg ListMaterialUnitConversionsParams) ([]ListMaterialUnitConversionsRow, error) {
	rows, err := q.db.Query(ctx, listMaterialUnitConversions,
		arg.MaterialID,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialUnitConversionsRow
	for rows.Next() {
		var i ListMaterialUnitConversionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.FromUnitID,
			&i.ToUnitID,
			&i.Factor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialUnitConversionExists = `-- name: MaterialUnitConversionExists :one
SELECT EXISTS (
    SELECT 1
    FROM material_unit_conversions
    WHERE material_id = $1::bigint
      AND from_unit_id = $2::bigint
      AND to_unit_id = $3::bigint
      AND deleted_at IS NULL
      AND ($4::bigint = 0 OR id <> $4::bigint)
) AS exists
`

type MaterialUnitConversionExistsParams struct {
	MaterialID int64 `db:"material_id" json:"material_id"`
	FromUnitID int64 `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64 `db:"to_unit_id" json:"to_unit_id"`
	ExcludeID  int64 `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) MaterialUnitConversionExists(ctx context.Context, arg MaterialUnitConversionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, materialUnitConversionExists,
		arg.MaterialID,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.ExcludeID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reverseMaterialUnitConversionExists = `-- name: ReverseMaterialUnitConversionExists :one
SELECT EXISTS (
    SELECT 1
    FROM material_unit_conversions
    WHERE material_id = $1::bigint
      AND from_unit_id = $2::bigint
      AND to_unit_id = $3::bigint
      AND deleted_at IS NULL
      AND ($4::bigint = 0 OR id <> $4::bigint)
) AS exists
`

type ReverseMaterialUnitConversionExistsParams struct {
	MaterialID int64 `db:"material_id" json:"material_id"`
	ToUnitID   int64 `db:"to_unit_id" json:"to_unit_id"`
	FromUnitID int64 `db:"from_unit_id" json:"from_unit_id"`
	ExcludeID  int64 `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) ReverseMaterialUnitConversionExists(ctx context.Context, arg ReverseMaterialUnitConversionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reverseMaterialUnitConversionExists,
		arg.MaterialID,
		arg.ToUnitID,
		arg.FromUnitID,
		arg.ExcludeID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteMaterialUnitConversion = `-- name: SoftDeleteMaterialUnitConversion :execrows
UPDATE material_unit_conversions
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1::bigint
  AND material_id = $2::bigint
  AND deleted_at IS NULL
`

type SoftDeleteMaterialUnitConversionParams struct {
	ID         int64 `db:"id" json:"id"`
	MaterialID int64 `db:"material_id" json:"material_id"`
}

func (q *Queries) SoftDeleteMaterialUnitConversion(ctx context.Context, arg SoftDeleteMaterialUnitConversionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMaterialUnitConversion, arg.ID, arg.MaterialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaterialUnitConversion = `-- name: UpdateMaterialUnitConversion :one
UPDATE material_unit_conversions
SET from_unit_id = $3,
    to_unit_id = $4,
    factor = $5,
    updated_at = NOW()
WHERE id = $1
  AND material_id = $2
  AND deleted_at IS NULL
RETURNING id,
          material_id,
          from_unit_id,
          to_unit_id,
          factor,
          created_at,
          updated_at
`

type UpdateMaterialUnitConversionParams struct {
	ID         int64          `db:"id" json:"id"`
	MaterialID int64          `db:"material_id" json:"material_id"`
	FromUnitID int64          `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64          `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric `db:"factor" json:"factor"`
}

type UpdateMaterialUnitConversionRow struct {
	ID         int64              `db:"id" json:"id"`
	MaterialID int64              `db:"material_id" json:"material_id"`
	FromUnitID int64              `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64              `db:"to_unit_id" json:"to_unit_id"`
	Factor     pgtype.Numeric     `db:"factor" json:"factor"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateMaterialUnitConversion(ctx context.Context, arg UpdateMaterialUnitConversionParams) (UpdateMaterialUnitConversionRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialUnitConversion,
		arg.ID,
		arg.MaterialID,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.Factor,
	)
	var i UpdateMaterialUnitConversionRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.Factor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
