// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: material_categories.sql

package materialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterialCategory = `-- name: CreateMaterialCategory :one
INSERT INTO material_categories (code, name, parent_id, status, remark)
VALUES ($1, $2, $3, $4, $5)
RETURNING id,
          code,
          name,
          parent_id,
          status,
          remark,
          created_at,
          updated_at
`

type CreateMaterialCategoryParams struct {
	Code     string  `db:"code" json:"code"`
	Name     string  `db:"name" json:"name"`
	ParentID *int64  `db:"parent_id" json:"parent_id"`
	Status   string  `db:"status" json:"status"`
	Remark   *string `db:"remark" json:"remark"`
}

type CreateMaterialCategoryRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	ParentID  *int64             `db:"parent_id" json:"parent_id"`
	Status    string             `db:"status" json:"status"`
	Remark    *string            `db:"remark" json:"remark"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateMaterialCategory(ctx context.Context, arg CreateMaterialCategoryParams) (CreateMaterialCategoryRow, error) {
	row := q.db.QueryRow(ctx, createMaterialCategory,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.Status,
		arg.Remark,
	)
	var i CreateMaterialCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialCategoryByID = `-- name: GetMaterialCategoryByID :one
SELECT id,
       code,
       name,
       parent_id,
       status,
       remark,
       created_at,
       updated_at
FROM material_categories
WHERE id = $1
  AND deleted_at IS NULL
`

type GetMaterialCategoryByIDRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	ParentID  *int64             `db:"parent_id" json:"parent_id"`
	Status    string             `db:"status" json:"status"`
	Remark    *string            `db:"remark" json:"remark"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMaterialCategoryByID(ctx context.Context, id int64) (GetMaterialCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getMaterialCategoryByID, id)
	var i GetMaterialCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterialCategories = `-- name: ListMaterialCategories :many
SELECT id,
       code,
       name,
       parent_id,
       status,
       remark,
       created_at,
       updated_at
FROM material_categories
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint IS NULL OR parent_id = $2::bigint)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListMaterialCategoriesParams struct {
	Status   *string `db:"status" json:"status"`
	ParentID *int64  `db:"parent_id" json:"parent_id"`
	Offset   int32   `db:"offset" json:"offset"`
	Limit    int32   `db:"limit" json:"limit"`
}

type ListMaterialCategoriesRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	ParentID  *int64             `db:"parent_id" json:"parent_id"`
	Status    string             `db:"status" json:"status"`
	Remark    *string            `db:"remark" json:"remark"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMaterialCategories(ctx context.Context, arg ListMaterialCategoriesParams) ([]ListMaterialCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listMaterialCategories,
		arg.Status,
		arg.ParentID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialCategoriesRow
	for rows.Next() {
		var i ListMaterialCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.Status,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialCategoryCodeExists = `-- name: MaterialCategoryCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM material_categories
    WHERE code = $1
      AND deleted_at IS NULL
      AND ($2::bigint = 0 OR id <> $2::bigint)
) AS exists
`

type MaterialCategoryCodeExistsParams struct {
	Code      string `db:"code" json:"code"`
	ExcludeID int64  `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) MaterialCategoryCodeExists(ctx context.Context, arg MaterialCategoryCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, materialCategoryCodeExists, arg.Code, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteMaterialCategory = `-- name: SoftDeleteMaterialCategory :execrows
UPDATE material_categories
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaterialCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMaterialCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaterialCategory = `-- name: UpdateMaterialCategory :one
UPDATE material_categories
SET code = $2,
    name = $3,
    parent_id = $4,
    status = $5,
    remark = $6,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          code,
          name,
          parent_id,
          status,
          remark,
          created_at,
          updated_at
`

type UpdateMaterialCategoryParams struct {
	ID       int64   `db:"id" json:"id"`
	Code     string  `db:"code" json:"code"`
	Name     string  `db:"name" json:"name"`
	ParentID *int64  `db:"parent_id" json:"parent_id"`
	Status   string  `db:"status" json:"status"`
	Remark   *string `db:"remark" json:"remark"`
}

type UpdateMaterialCategoryRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	ParentID  *int64             `db:"parent_id" json:"parent_id"`
	Status    string             `db:"status" json:"status"`
	Remark    *string            `db:"remark" json:"remark"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateMaterialCategory(ctx context.Context, arg UpdateMaterialCategoryParams) (UpdateMaterialCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateMaterialCategory,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.Status,
		arg.Remark,
	)
	var i UpdateMaterialCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Status,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
