// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package materialdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Material master data
type Material struct {
	ID int64 `db:"id" json:"id"`
	// Unique material code among non-deleted materials
	Code string `db:"code" json:"code"`
	Name string `db:"name" json:"name"`
	// Material category id
	CategoryID int64 `db:"category_id" json:"category_id"`
	// Material base unit id
	BaseUnitID int64              `db:"base_unit_id" json:"base_unit_id"`
	Status     string             `db:"status" json:"status"`
	Remark     *string            `db:"remark" json:"remark"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Category-specific material attribute definitions
type MaterialAttributeDefinition struct {
	ID         int64  `db:"id" json:"id"`
	CategoryID int64  `db:"category_id" json:"category_id"`
	Code       string `db:"code" json:"code"`
	Name       string `db:"name" json:"name"`
	// Attribute data type: text, number, boolean, date, option
	DataType  string             `db:"data_type" json:"data_type"`
	Required  bool               `db:"required" json:"required"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Material attribute values
type MaterialAttributeValue struct {
	ID         int64 `db:"id" json:"id"`
	MaterialID int64 `db:"material_id" json:"material_id"`
	// Material attribute definition id
	DefinitionID int64              `db:"definition_id" json:"definition_id"`
	ValueText    *string            `db:"value_text" json:"value_text"`
	ValueNumber  pgtype.Numeric     `db:"value_number" json:"value_number"`
	ValueBoolean *bool              `db:"value_boolean" json:"value_boolean"`
	ValueDate    pgtype.Date        `db:"value_date" json:"value_date"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Material category master data
type MaterialCategory struct {
	ID int64 `db:"id" json:"id"`
	// Unique category code among non-deleted categories
	Code string `db:"code" json:"code"`
	Name string `db:"name" json:"name"`
	// Parent material category id
	ParentID  *int64             `db:"parent_id" json:"parent_id"`
	Status    string             `db:"status" json:"status"`
	Remark    *string            `db:"remark" json:"remark"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Material-specific unit conversion rules
type MaterialUnitConversion struct {
	ID         int64 `db:"id" json:"id"`
	MaterialID int64 `db:"material_id" json:"material_id"`
	FromUnitID int64 `db:"from_unit_id" json:"from_unit_id"`
	ToUnitID   int64 `db:"to_unit_id" json:"to_unit_id"`
	// Conversion factor from source unit to target unit
	Factor    pgtype.Numeric     `db:"factor" json:"factor"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Reusable measurement units
type Unit struct {
	ID int64 `db:"id" json:"id"`
	// Unique unit code among non-deleted units
	Code   string `db:"code" json:"code"`
	Name   string `db:"name" json:"name"`
	Symbol string `db:"symbol" json:"symbol"`
	// Unit type: count, weight, length, area, volume, package, time, other
	UnitType string `db:"unit_type" json:"unit_type"`
	// Allowed quantity decimal places
	Precision int32              `db:"precision" json:"precision"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Soft delete marker. NULL means not deleted
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
