// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package materialdb

import (
	"context"
)

type Querier interface {
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (CreateMaterialRow, error)
	GetMaterialByID(ctx context.Context, id int64) (GetMaterialByIDRow, error)
	ListMaterials(ctx context.Context, arg ListMaterialsParams) ([]ListMaterialsRow, error)
	MaterialCategoryExists(ctx context.Context, id int64) (bool, error)
	MaterialCodeExists(ctx context.Context, arg MaterialCodeExistsParams) (bool, error)
	SoftDeleteMaterial(ctx context.Context, id int64) (int64, error)
	UnitExists(ctx context.Context, id int64) (bool, error)
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (UpdateMaterialRow, error)
}

var _ Querier = (*Queries)(nil)
