// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: units.sql

package materialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (code, name, symbol, unit_type, precision, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id,
          code,
          name,
          symbol,
          unit_type,
          precision,
          status,
          created_at,
          updated_at
`

type CreateUnitParams struct {
	Code      string `db:"code" json:"code"`
	Name      string `db:"name" json:"name"`
	Symbol    string `db:"symbol" json:"symbol"`
	UnitType  string `db:"unit_type" json:"unit_type"`
	Precision int32  `db:"precision" json:"precision"`
	Status    string `db:"status" json:"status"`
}

type CreateUnitRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	Symbol    string             `db:"symbol" json:"symbol"`
	UnitType  string             `db:"unit_type" json:"unit_type"`
	Precision int32              `db:"precision" json:"precision"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (CreateUnitRow, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.UnitType,
		arg.Precision,
		arg.Status,
	)
	var i CreateUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitType,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id,
       code,
       name,
       symbol,
       unit_type,
       precision,
       status,
       created_at,
       updated_at
FROM units
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUnitByIDRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	Symbol    string             `db:"symbol" json:"symbol"`
	UnitType  string             `db:"unit_type" json:"unit_type"`
	Precision int32              `db:"precision" json:"precision"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUnitByID(ctx context.Context, id int64) (GetUnitByIDRow, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i GetUnitByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitType,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id,
       code,
       name,
       symbol,
       unit_type,
       precision,
       status,
       created_at,
       updated_at
FROM units
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR unit_type = $2::text)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListUnitsParams struct {
	Status   *string `db:"status" json:"status"`
	UnitType *string `db:"unit_type" json:"unit_type"`
	Offset   int32   `db:"offset" json:"offset"`
	Limit    int32   `db:"limit" json:"limit"`
}

type ListUnitsRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	Symbol    string             `db:"symbol" json:"symbol"`
	UnitType  string             `db:"unit_type" json:"unit_type"`
	Precision int32              `db:"precision" json:"precision"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.Status,
		arg.UnitType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitsRow
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.UnitType,
			&i.Precision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUnit = `-- name: SoftDeleteUnit :execrows
UPDATE units
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUnit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unitCodeExists = `-- name: UnitCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM units
    WHERE code = $1
      AND deleted_at IS NULL
      AND ($2::bigint = 0 OR id <> $2::bigint)
) AS exists
`

type UnitCodeExistsParams struct {
	Code      string `db:"code" json:"code"`
	ExcludeID int64  `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) UnitCodeExists(ctx context.Context, arg UnitCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, unitCodeExists, arg.Code, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET code = $2,
    name = $3,
    symbol = $4,
    unit_type = $5,
    precision = $6,
    status = $7,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id,
          code,
          name,
          symbol,
          unit_type,
          precision,
          status,
          created_at,
          updated_at
`

type UpdateUnitParams struct {
	ID        int64  `db:"id" json:"id"`
	Code      string `db:"code" json:"code"`
	Name      string `db:"name" json:"name"`
	Symbol    string `db:"symbol" json:"symbol"`
	UnitType  string `db:"unit_type" json:"unit_type"`
	Precision int32  `db:"precision" json:"precision"`
	Status    string `db:"status" json:"status"`
}

type UpdateUnitRow struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	Symbol    string             `db:"symbol" json:"symbol"`
	UnitType  string             `db:"unit_type" json:"unit_type"`
	Precision int32              `db:"precision" json:"precision"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (UpdateUnitRow, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.UnitType,
		arg.Precision,
		arg.Status,
	)
	var i UpdateUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitType,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
