// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventory_stocks.sql

package inventorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryStock = `-- name: GetInventoryStock :one
SELECT warehouse_id,
       sku_id,
       on_hand_qty,
       reserved_qty,
       (on_hand_qty - reserved_qty)::numeric AS available_qty,
       updated_at
FROM inventory_stocks
WHERE warehouse_id = $1::bigint
  AND sku_id = $2::bigint
  AND deleted_at IS NULL
`

type GetInventoryStockParams struct {
	WarehouseID int64 `db:"warehouse_id" json:"warehouse_id"`
	SkuID       int64 `db:"sku_id" json:"sku_id"`
}

type GetInventoryStockRow struct {
	WarehouseID  int64              `db:"warehouse_id" json:"warehouse_id"`
	SkuID        int64              `db:"sku_id" json:"sku_id"`
	OnHandQty    pgtype.Numeric     `db:"on_hand_qty" json:"on_hand_qty"`
	ReservedQty  pgtype.Numeric     `db:"reserved_qty" json:"reserved_qty"`
	AvailableQty pgtype.Numeric     `db:"available_qty" json:"available_qty"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetInventoryStock(ctx context.Context, arg GetInventoryStockParams) (GetInventoryStockRow, error) {
	row := q.db.QueryRow(ctx, getInventoryStock, arg.WarehouseID, arg.SkuID)
	var i GetInventoryStockRow
	err := row.Scan(
		&i.WarehouseID,
		&i.SkuID,
		&i.OnHandQty,
		&i.ReservedQty,
		&i.AvailableQty,
		&i.UpdatedAt,
	)
	return i, err
}

const inventoryBatchExistsForSKU = `-- name: InventoryBatchExistsForSKU :one
SELECT EXISTS (
    SELECT 1
    FROM inventory_batches
    WHERE id = $1::bigint
      AND sku_id = $2::bigint
      AND deleted_at IS NULL
) AS exists
`

type InventoryBatchExistsForSKUParams struct {
	BatchID int64 `db:"batch_id" json:"batch_id"`
	SkuID   int64 `db:"sku_id" json:"sku_id"`
}

func (q *Queries) InventoryBatchExistsForSKU(ctx context.Context, arg InventoryBatchExistsForSKUParams) (bool, error) {
	row := q.db.QueryRow(ctx, inventoryBatchExistsForSKU, arg.BatchID, arg.SkuID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInventoryStockLayers = `-- name: ListInventoryStockLayers :many
SELECT id,
       warehouse_id,
       sku_id,
       batch_id,
       received_at,
       on_hand_qty,
       reserved_qty,
       (on_hand_qty - reserved_qty)::numeric AS available_qty,
       created_at,
       updated_at
FROM inventory_stock_layers
WHERE warehouse_id = $1::bigint
  AND sku_id = $2::bigint
  AND deleted_at IS NULL
  AND ($3::bigint IS NULL OR batch_id = $3::bigint)
ORDER BY received_at, id
LIMIT $5 OFFSET $4
`

type ListInventoryStockLayersParams struct {
	WarehouseID int64  `db:"warehouse_id" json:"warehouse_id"`
	SkuID       int64  `db:"sku_id" json:"sku_id"`
	BatchID     *int64 `db:"batch_id" json:"batch_id"`
	Offset      int32  `db:"offset" json:"offset"`
	Limit       int32  `db:"limit" json:"limit"`
}

type ListInventoryStockLayersRow struct {
	ID           int64              `db:"id" json:"id"`
	WarehouseID  int64              `db:"warehouse_id" json:"warehouse_id"`
	SkuID        int64              `db:"sku_id" json:"sku_id"`
	BatchID      *int64             `db:"batch_id" json:"batch_id"`
	ReceivedAt   pgtype.Timestamptz `db:"received_at" json:"received_at"`
	OnHandQty    pgtype.Numeric     `db:"on_hand_qty" json:"on_hand_qty"`
	ReservedQty  pgtype.Numeric     `db:"reserved_qty" json:"reserved_qty"`
	AvailableQty pgtype.Numeric     `db:"available_qty" json:"available_qty"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListInventoryStockLayers(ctx context.Context, arg ListInventoryStockLayersParams) ([]ListInventoryStockLayersRow, error) {
	rows, err := q.db.Query(ctx, listInventoryStockLayers,
		arg.WarehouseID,
		arg.SkuID,
		arg.BatchID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryStockLayersRow
	for rows.Next() {
		var i ListInventoryStockLayersRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.SkuID,
			&i.BatchID,
			&i.ReceivedAt,
			&i.OnHandQty,
			&i.ReservedQty,
			&i.AvailableQty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryStocks = `-- name: ListInventoryStocks :many
SELECT warehouse_id,
       sku_id,
       on_hand_qty,
       reserved_qty,
       (on_hand_qty - reserved_qty)::numeric AS available_qty,
       updated_at
FROM inventory_stocks
WHERE deleted_at IS NULL
  AND ($1::bigint IS NULL OR warehouse_id = $1::bigint)
  AND ($2::bigint IS NULL OR sku_id = $2::bigint)
ORDER BY warehouse_id, sku_id
LIMIT $4 OFFSET $3
`

type ListInventoryStocksParams struct {
	WarehouseID *int64 `db:"warehouse_id" json:"warehouse_id"`
	SkuID       *int64 `db:"sku_id" json:"sku_id"`
	Offset      int32  `db:"offset" json:"offset"`
	Limit       int32  `db:"limit" json:"limit"`
}

type ListInventoryStocksRow struct {
	WarehouseID  int64              `db:"warehouse_id" json:"warehouse_id"`
	SkuID        int64              `db:"sku_id" json:"sku_id"`
	OnHandQty    pgtype.Numeric     `db:"on_hand_qty" json:"on_hand_qty"`
	ReservedQty  pgtype.Numeric     `db:"reserved_qty" json:"reserved_qty"`
	AvailableQty pgtype.Numeric     `db:"available_qty" json:"available_qty"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListInventoryStocks(ctx context.Context, arg ListInventoryStocksParams) ([]ListInventoryStocksRow, error) {
	rows, err := q.db.Query(ctx, listInventoryStocks,
		arg.WarehouseID,
		arg.SkuID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryStocksRow
	for rows.Next() {
		var i ListInventoryStocksRow
		if err := rows.Scan(
			&i.WarehouseID,
			&i.SkuID,
			&i.OnHandQty,
			&i.ReservedQty,
			&i.AvailableQty,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sKUExistsForInventory = `-- name: SKUExistsForInventory :one
SELECT EXISTS (
    SELECT 1
    FROM skus
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) SKUExistsForInventory(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, sKUExistsForInventory, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const warehouseExistsForInventory = `-- name: WarehouseExistsForInventory :one
SELECT EXISTS (
    SELECT 1
    FROM warehouses
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) WarehouseExistsForInventory(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, warehouseExistsForInventory, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
