// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package inventorydb

import (
	"context"
)

type Querier interface {
	GetInventoryStock(ctx context.Context, arg GetInventoryStockParams) (GetInventoryStockRow, error)
	InventoryBatchExistsForSKU(ctx context.Context, arg InventoryBatchExistsForSKUParams) (bool, error)
	ListInventoryStockLayers(ctx context.Context, arg ListInventoryStockLayersParams) ([]ListInventoryStockLayersRow, error)
	ListInventoryStocks(ctx context.Context, arg ListInventoryStocksParams) ([]ListInventoryStocksRow, error)
	SKUExistsForInventory(ctx context.Context, id int64) (bool, error)
	WarehouseExistsForInventory(ctx context.Context, id int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
