// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockAPISecret = `-- name: BlockAPISecret :one
UPDATE api_secrets
SET status = 'blocked',
    updated_at = NOW()
WHERE api_app_id = $1
  AND secret_id = $2
  AND deleted_at IS NULL
RETURNING id, api_app_id, secret_id, name, status, bound_metadata, expires_at, last_used_at, created_at, updated_at
`

type BlockAPISecretParams struct {
	ApiAppID int64  `db:"api_app_id" json:"api_app_id"`
	SecretID string `db:"secret_id" json:"secret_id"`
}

type BlockAPISecretRow struct {
	ID            int64              `db:"id" json:"id"`
	ApiAppID      int64              `db:"api_app_id" json:"api_app_id"`
	SecretID      string             `db:"secret_id" json:"secret_id"`
	Name          string             `db:"name" json:"name"`
	Status        string             `db:"status" json:"status"`
	BoundMetadata []byte             `db:"bound_metadata" json:"bound_metadata"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) BlockAPISecret(ctx context.Context, arg BlockAPISecretParams) (BlockAPISecretRow, error) {
	row := q.db.QueryRow(ctx, blockAPISecret, arg.ApiAppID, arg.SecretID)
	var i BlockAPISecretRow
	err := row.Scan(
		&i.ID,
		&i.ApiAppID,
		&i.SecretID,
		&i.Name,
		&i.Status,
		&i.BoundMetadata,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeAdminPassword = `-- name: ChangeAdminPassword :execrows
UPDATE admin_users
SET password_hash = $2,
    must_change_password = FALSE,
    password_changed_at = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type ChangeAdminPasswordParams struct {
	ID                int64              `db:"id" json:"id"`
	PasswordHash      string             `db:"password_hash" json:"password_hash"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
}

func (q *Queries) ChangeAdminPassword(ctx context.Context, arg ChangeAdminPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeAdminPassword, arg.ID, arg.PasswordHash, arg.PasswordChangedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAPIApp = `-- name: CreateAPIApp :one
INSERT INTO api_apps (app_id, name, description, status, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, app_id, name, description, status, metadata, created_at, updated_at
`

type CreateAPIAppParams struct {
	AppID       string  `db:"app_id" json:"app_id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	Status      string  `db:"status" json:"status"`
	Metadata    []byte  `db:"metadata" json:"metadata"`
}

type CreateAPIAppRow struct {
	ID          int64              `db:"id" json:"id"`
	AppID       string             `db:"app_id" json:"app_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAPIApp(ctx context.Context, arg CreateAPIAppParams) (CreateAPIAppRow, error) {
	row := q.db.QueryRow(ctx, createAPIApp,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i CreateAPIAppRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAPISecret = `-- name: CreateAPISecret :one
INSERT INTO api_secrets (
    api_app_id,
    secret_id,
    secret_hash,
    name,
    status,
    bound_metadata,
    expires_at
)
VALUES ($1, $2, $3, $4, 'active', $5, $6)
RETURNING id, api_app_id, secret_id, name, status, bound_metadata, expires_at, last_used_at, created_at, updated_at
`

type CreateAPISecretParams struct {
	ApiAppID      int64              `db:"api_app_id" json:"api_app_id"`
	SecretID      string             `db:"secret_id" json:"secret_id"`
	SecretHash    string             `db:"secret_hash" json:"secret_hash"`
	Name          string             `db:"name" json:"name"`
	BoundMetadata []byte             `db:"bound_metadata" json:"bound_metadata"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type CreateAPISecretRow struct {
	ID            int64              `db:"id" json:"id"`
	ApiAppID      int64              `db:"api_app_id" json:"api_app_id"`
	SecretID      string             `db:"secret_id" json:"secret_id"`
	Name          string             `db:"name" json:"name"`
	Status        string             `db:"status" json:"status"`
	BoundMetadata []byte             `db:"bound_metadata" json:"bound_metadata"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAPISecret(ctx context.Context, arg CreateAPISecretParams) (CreateAPISecretRow, error) {
	row := q.db.QueryRow(ctx, createAPISecret,
		arg.ApiAppID,
		arg.SecretID,
		arg.SecretHash,
		arg.Name,
		arg.BoundMetadata,
		arg.ExpiresAt,
	)
	var i CreateAPISecretRow
	err := row.Scan(
		&i.ID,
		&i.ApiAppID,
		&i.SecretID,
		&i.Name,
		&i.Status,
		&i.BoundMetadata,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIAppByID = `-- name: GetAPIAppByID :one
SELECT id, app_id, name, description, status, metadata, created_at, updated_at
FROM api_apps
WHERE id = $1
  AND deleted_at IS NULL
`

type GetAPIAppByIDRow struct {
	ID          int64              `db:"id" json:"id"`
	AppID       string             `db:"app_id" json:"app_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAPIAppByID(ctx context.Context, id int64) (GetAPIAppByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIAppByID, id)
	var i GetAPIAppByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIAppByIdentifier = `-- name: GetAPIAppByIdentifier :one
SELECT id, app_id, name, description, status, metadata, created_at, updated_at
FROM api_apps
WHERE app_id = $1
  AND deleted_at IS NULL
`

type GetAPIAppByIdentifierRow struct {
	ID          int64              `db:"id" json:"id"`
	AppID       string             `db:"app_id" json:"app_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAPIAppByIdentifier(ctx context.Context, appID string) (GetAPIAppByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getAPIAppByIdentifier, appID)
	var i GetAPIAppByIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, password_initialized, must_change_password, password_changed_at, status, created_at, updated_at
FROM admin_users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetAdminByIDRow struct {
	ID                  int64              `db:"id" json:"id"`
	Username            string             `db:"username" json:"username"`
	PasswordHash        string             `db:"password_hash" json:"password_hash"`
	PasswordInitialized bool               `db:"password_initialized" json:"password_initialized"`
	MustChangePassword  bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt   pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	Status              string             `db:"status" json:"status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (GetAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i GetAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordInitialized,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, password_initialized, must_change_password, password_changed_at, status, created_at, updated_at
FROM admin_users
WHERE username = $1
  AND deleted_at IS NULL
`

type GetAdminByUsernameRow struct {
	ID                  int64              `db:"id" json:"id"`
	Username            string             `db:"username" json:"username"`
	PasswordHash        string             `db:"password_hash" json:"password_hash"`
	PasswordInitialized bool               `db:"password_initialized" json:"password_initialized"`
	MustChangePassword  bool               `db:"must_change_password" json:"must_change_password"`
	PasswordChangedAt   pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	Status              string             `db:"status" json:"status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (GetAdminByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i GetAdminByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordInitialized,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeAdminPassword = `-- name: InitializeAdminPassword :one
UPDATE admin_users
SET password_hash = $2,
    password_initialized = TRUE,
    must_change_password = TRUE,
    password_changed_at = NULL,
    updated_at = NOW()
WHERE username = $1
  AND password_initialized = FALSE
  AND deleted_at IS NULL
RETURNING id
`

type InitializeAdminPasswordParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) InitializeAdminPassword(ctx context.Context, arg InitializeAdminPasswordParams) (int64, error) {
	row := q.db.QueryRow(ctx, initializeAdminPassword, arg.Username, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAPIApps = `-- name: ListAPIApps :many
SELECT id, app_id, name, description, status, metadata, created_at, updated_at
FROM api_apps
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
ORDER BY id
LIMIT $3
OFFSET $2
`

type ListAPIAppsParams struct {
	Status     *string `db:"status" json:"status"`
	PageOffset int32   `db:"page_offset" json:"page_offset"`
	PageLimit  int32   `db:"page_limit" json:"page_limit"`
}

type ListAPIAppsRow struct {
	ID          int64              `db:"id" json:"id"`
	AppID       string             `db:"app_id" json:"app_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAPIApps(ctx context.Context, arg ListAPIAppsParams) ([]ListAPIAppsRow, error) {
	rows, err := q.db.Query(ctx, listAPIApps, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIAppsRow
	for rows.Next() {
		var i ListAPIAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPISecrets = `-- name: ListAPISecrets :many
SELECT id, api_app_id, secret_id, name, status, bound_metadata, expires_at, last_used_at, created_at, updated_at
FROM api_secrets
WHERE api_app_id = $1
  AND deleted_at IS NULL
ORDER BY id
`

type ListAPISecretsRow struct {
	ID            int64              `db:"id" json:"id"`
	ApiAppID      int64              `db:"api_app_id" json:"api_app_id"`
	SecretID      string             `db:"secret_id" json:"secret_id"`
	Name          string             `db:"name" json:"name"`
	Status        string             `db:"status" json:"status"`
	BoundMetadata []byte             `db:"bound_metadata" json:"bound_metadata"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAPISecrets(ctx context.Context, apiAppID int64) ([]ListAPISecretsRow, error) {
	rows, err := q.db.Query(ctx, listAPISecrets, apiAppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPISecretsRow
	for rows.Next() {
		var i ListAPISecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiAppID,
			&i.SecretID,
			&i.Name,
			&i.Status,
			&i.BoundMetadata,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPISecretsForAuthentication = `-- name: ListAPISecretsForAuthentication :many
SELECT id, api_app_id, secret_id, secret_hash, name, status, bound_metadata, expires_at, last_used_at, created_at, updated_at
FROM api_secrets
WHERE api_app_id = $1
  AND deleted_at IS NULL
ORDER BY id
`

type ListAPISecretsForAuthenticationRow struct {
	ID            int64              `db:"id" json:"id"`
	ApiAppID      int64              `db:"api_app_id" json:"api_app_id"`
	SecretID      string             `db:"secret_id" json:"secret_id"`
	SecretHash    string             `db:"secret_hash" json:"secret_hash"`
	Name          string             `db:"name" json:"name"`
	Status        string             `db:"status" json:"status"`
	BoundMetadata []byte             `db:"bound_metadata" json:"bound_metadata"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAPISecretsForAuthentication(ctx context.Context, apiAppID int64) ([]ListAPISecretsForAuthenticationRow, error) {
	rows, err := q.db.Query(ctx, listAPISecretsForAuthentication, apiAppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPISecretsForAuthenticationRow
	for rows.Next() {
		var i ListAPISecretsForAuthenticationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiAppID,
			&i.SecretID,
			&i.SecretHash,
			&i.Name,
			&i.Status,
			&i.BoundMetadata,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAPIApp = `-- name: SoftDeleteAPIApp :execrows
UPDATE api_apps
SET deleted_at = NOW(),
    status = 'inactive',
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAPIApp(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAPIApp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPISecretLastUsed = `-- name: TouchAPISecretLastUsed :execrows
UPDATE api_secrets
SET last_used_at = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

type TouchAPISecretLastUsedParams struct {
	ID         int64              `db:"id" json:"id"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) TouchAPISecretLastUsed(ctx context.Context, arg TouchAPISecretLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAPISecretLastUsed, arg.ID, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIApp = `-- name: UpdateAPIApp :one
UPDATE api_apps
SET name = $2,
    description = $3,
    status = $4,
    metadata = $5,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, app_id, name, description, status, metadata, created_at, updated_at
`

type UpdateAPIAppParams struct {
	ID          int64   `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	Status      string  `db:"status" json:"status"`
	Metadata    []byte  `db:"metadata" json:"metadata"`
}

type UpdateAPIAppRow struct {
	ID          int64              `db:"id" json:"id"`
	AppID       string             `db:"app_id" json:"app_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateAPIApp(ctx context.Context, arg UpdateAPIAppParams) (UpdateAPIAppRow, error) {
	row := q.db.QueryRow(ctx, updateAPIApp,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i UpdateAPIAppRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
