// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authdb

import (
	"context"
)

type Querier interface {
	BlockAPISecret(ctx context.Context, arg BlockAPISecretParams) (BlockAPISecretRow, error)
	ChangeAdminPassword(ctx context.Context, arg ChangeAdminPasswordParams) (int64, error)
	CreateAPIApp(ctx context.Context, arg CreateAPIAppParams) (CreateAPIAppRow, error)
	CreateAPISecret(ctx context.Context, arg CreateAPISecretParams) (CreateAPISecretRow, error)
	GetAPIAppByID(ctx context.Context, id int64) (GetAPIAppByIDRow, error)
	GetAPIAppByIdentifier(ctx context.Context, appID string) (GetAPIAppByIdentifierRow, error)
	GetAdminByID(ctx context.Context, id int64) (GetAdminByIDRow, error)
	GetAdminByUsername(ctx context.Context, username string) (GetAdminByUsernameRow, error)
	InitializeAdminPassword(ctx context.Context, arg InitializeAdminPasswordParams) (InitializeAdminPasswordRow, error)
	ListAPIApps(ctx context.Context, arg ListAPIAppsParams) ([]ListAPIAppsRow, error)
	ListAPISecrets(ctx context.Context, apiAppID int64) ([]ListAPISecretsRow, error)
	ListAPISecretsForAuthentication(ctx context.Context, apiAppID int64) ([]ListAPISecretsForAuthenticationRow, error)
	SoftDeleteAPIApp(ctx context.Context, id int64) (int64, error)
	TouchAPISecretLastUsed(ctx context.Context, arg TouchAPISecretLastUsedParams) (int64, error)
	UpdateAPIApp(ctx context.Context, arg UpdateAPIAppParams) (UpdateAPIAppRow, error)
}

var _ Querier = (*Queries)(nil)
